package universidadejemplo.Vistas;

import com.toedter.calendar.JDateChooser;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import universidadejemplo.AccesoADatos.AlumnoData;
import universidadejemplo.Entidades.Alumno;

/**
 *
 * @author luz
 */
public class GestionDeAlumnos extends javax.swing.JInternalFrame {

    DateTimeFormatter format = new DateTimeFormatterBuilder().append(DateTimeFormatter.ofPattern("dd-MMM-yyyy")).toFormatter();
    SimpleDateFormat formate = new SimpleDateFormat("dd-MMM-yyyy");
    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MMM-dd");
    AlumnoData adata = new AlumnoData();
    String fechaString;
    Date fecha;
    Alumno alumno;
    private boolean activo;

    public GestionDeAlumnos() {
        initComponents();
        cargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jFileChooser1 = new javax.swing.JFileChooser();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        JLAlumno = new javax.swing.JLabel();
        JLDocumento = new javax.swing.JLabel();
        jtDoc = new javax.swing.JTextField();
        JBBuscar = new javax.swing.JButton();
        JLApellido = new javax.swing.JLabel();
        jtApe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jrActivo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jbNuevo = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jdFN = new com.toedter.calendar.JDateChooser();
        radioButtonCrear = new javax.swing.JRadioButton();
        radioButtonBuscar = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jLabel2.setText("jLabel2");

        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(0, 153, 102));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        JLAlumno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLAlumno.setText("Alumno");

        JLDocumento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLDocumento.setText("Documento:");

        jtDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDocActionPerformed(evt);
            }
        });
        jtDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtDocKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtDocKeyTyped(evt);
            }
        });

        JBBuscar.setText("Buscar");
        JBBuscar.setEnabled(false);
        JBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBuscarActionPerformed(evt);
            }
        });

        JLApellido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLApellido.setText("Apellido:");

        jtApe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtApeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtApeKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        jtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomActionPerformed(evt);
            }
        });
        jtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtNomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNomKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Estado:");

        jrActivo.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("FechaDeNacimiento:");

        jbNuevo.setText("Limpiar");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.setEnabled(false);
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.setEnabled(false);
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jdFN.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdFNPropertyChange(evt);
            }
        });
        jdFN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jdFNKeyReleased(evt);
            }
        });

        buttonGroup1.add(radioButtonCrear);
        radioButtonCrear.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        radioButtonCrear.setText("CREAR");
        radioButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonCrearActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButtonBuscar);
        radioButtonBuscar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        radioButtonBuscar.setText("BUSCAR / ELIMINAR");
        radioButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonBuscarActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setEnabled(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrActivo)
                            .addComponent(jtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtApe, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdFN, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(205, 205, 205))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jbNuevo)
                        .addGap(36, 36, 36)
                        .addComponent(jbEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbGuardar)
                        .addGap(49, 49, 49)
                        .addComponent(jButton4)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JLApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JLDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addComponent(JBBuscar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioButtonCrear)
                                        .addGap(67, 67, 67)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JLAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(radioButtonBuscar))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLAlumno)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonCrear)
                    .addComponent(radioButtonBuscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(JBBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLDocumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLApellido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrActivo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbNuevo)
                                    .addComponent(jbEliminar)
                                    .addComponent(jbGuardar)
                                    .addComponent(jButton4)))))
                    .addComponent(jLabel4))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDocActionPerformed

    private void jtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        nuevoLimpiar();
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        guardarAlumnos();
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDocKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || jtDoc.getText().length() >= 8) {
            evt.consume();
        } else {
            jComboBox1.setSelectedIndex(0);
            jtApe.setText("");
            jtNom.setText("");
            jdFN.setDate(null);
            jrActivo.setSelected(false);
            JBBuscar.setEnabled(true);
        }
        if (jtDoc.getText().length() >=7) {
            if (radioButtonBuscar.isSelected()) {
                JBBuscar.setEnabled(true);
            }
        } else {
            JBBuscar.setEnabled(false);
            jbEliminar.setEnabled(false);
        }
    }//GEN-LAST:event_jtDocKeyTyped

    private void jtApeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtApeKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE) && !(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtApeKeyTyped

    private void jtNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE) && !(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtNomKeyTyped

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        eliminarAlumnos();
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void JBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBuscarActionPerformed
        if (jComboBox1.getSelectedIndex() != 0) {
            alumno = (Alumno) jComboBox1.getSelectedItem();
        } else {
            alumno = adata.buscarAlumnoPorDni(Integer.valueOf(jtDoc.getText()));
        }
        buscarAlumnoDni();
    }//GEN-LAST:event_JBBuscarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void radioButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonCrearActionPerformed
        nuevoLimpiar();
        jComboBox1.setEnabled(false);
        jtApe.setEnabled(true);
        jtApe.setEditable(true);
        jtNom.setEnabled(true);
        jtNom.setEditable(true);
        jrActivo.setEnabled(true);
        jdFN.setEnabled(true);

    }//GEN-LAST:event_radioButtonCrearActionPerformed

    private void radioButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonBuscarActionPerformed
        nuevoLimpiar();
        jComboBox1.setEnabled(true);
        jtApe.setEnabled(false);
        jtApe.setEditable(false);
        jtNom.setEnabled(false);
        jtNom.setEditable(false);
        jrActivo.setEnabled(false);
        jdFN.setEnabled(false);
    }//GEN-LAST:event_radioButtonBuscarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jbEliminar.setEnabled(false);
        
        if (jComboBox1.getSelectedIndex() != 0) {
            alumno = (Alumno) jComboBox1.getSelectedItem();
            JBBuscar.setEnabled(true);
            jtDoc.setText("");
        } else {
            JBBuscar.setEnabled(false);
            }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jtDocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDocKeyReleased
        activarBotonGuardar();
    }//GEN-LAST:event_jtDocKeyReleased

    private void jtApeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtApeKeyReleased
        activarBotonGuardar();
    }//GEN-LAST:event_jtApeKeyReleased

    private void jtNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomKeyReleased
        activarBotonGuardar();
    }//GEN-LAST:event_jtNomKeyReleased

    private void jdFNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdFNKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jdFNKeyReleased

    private void jdFNPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdFNPropertyChange
        activarBotonGuardar();
    }//GEN-LAST:event_jdFNPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBBuscar;
    private javax.swing.JLabel JLAlumno;
    private javax.swing.JLabel JLApellido;
    private javax.swing.JLabel JLDocumento;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<Object> jComboBox1;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private com.toedter.calendar.JDateChooser jdFN;
    private javax.swing.JRadioButton jrActivo;
    private javax.swing.JTextField jtApe;
    private javax.swing.JTextField jtDoc;
    private javax.swing.JTextField jtNom;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JRadioButton radioButtonBuscar;
    private javax.swing.JRadioButton radioButtonCrear;
    // End of variables declaration//GEN-END:variables
    public void getFecha() {
        if (jdFN.getDate() != null) {
            fechaString = formato.format(jdFN.getDate());
        }
    }

    public void buscarAlumnoDni() {

        if (alumno != null) {
            jbEliminar.setEnabled(true);
            jtApe.setEnabled(true);
            jtApe.setEditable(false);
            jtNom.setEnabled(true);
            jtNom.setEditable(false);
            jrActivo.setEnabled(true);
            jdFN.setEnabled(true);

            jtDoc.setText(alumno.getDni() + "");
            jtApe.setText(alumno.getApellido());
            jtNom.setText(alumno.getNombre());
            jrActivo.setSelected(alumno.isActivo());
            fechaString = alumno.getFechaNac().format(format);
            try {
                fecha = (Date) formate.parse(fechaString);
            } catch (ParseException ex) {
                Logger.getLogger(GestionDeAlumnos.class.getName()).log(Level.SEVERE, null, ex);
            }
            jdFN.setDate(fecha);
        } else {
            
            jbEliminar.setEnabled(false);
        }
    }

    public void nuevoLimpiar() {
        jtDoc.setText("");
        jtApe.setText("");
        jtNom.setText("");
        jdFN.setCalendar(null);
        jrActivo.setSelected(false);
        jComboBox1.setSelectedIndex(0);
        radioButtonBuscar.setSelected(false);
        radioButtonCrear.setSelected(false);
        jtApe.setEnabled(false);
        jtNom.setEnabled(false);
        jrActivo.setEnabled(false);
        jdFN.setEnabled(false);
        cargarComboBox();

    }

    public void eliminarAlumnos() {
        alumno.getIdAlumno();
        adata.eliminarX(alumno.getIdAlumno());
        nuevoLimpiar();

    }

    public void guardarAlumnos() {
        getFecha();
        DateTimeFormatter format = new DateTimeFormatterBuilder().append(DateTimeFormatter.ofPattern("yyyy-MMM-dd")).toFormatter();
        LocalDate fecha = LocalDate.parse(fechaString, format);
        Alumno alumno = new Alumno(Integer.parseInt(jtDoc.getText()), jtApe.getText(),
                jtNom.getText(), fecha, jrActivo.isSelected());
        adata.guardarAlumnoX(alumno);
        nuevoLimpiar();
    }

    private void cargarComboBox() {

        jComboBox1.removeAllItems();
        jComboBox1.addItem("--Seleccione un alumno--");
        for (Object alu : adata.listarAlumnos()) {
            jComboBox1.addItem(alu);

        }
    }

    private void activarBotonGuardar() {
        if (radioButtonCrear.isSelected()) {
            if (jtDoc.getText().length() == 8
                    && jtNom.getText().length() >= 3
                    && jtApe.getText().length() >= 2
                    && jdFN.getDate() != null) {
                jbGuardar.setEnabled(true);
                jrActivo.setSelected(true);
            } else {
                jbGuardar.setEnabled(false);
            }
        }
    }
}
